[project]
name = "influxdb-sdk"
version = "0.1.0"
description = "A package that depends on the `influxdb-client`, for the db management."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "influxdb-client>=1.49.0",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "tqdm>=4.67.1",
    "uv>=0.9.11",
]
